* Tempo, atenção e tédio
** Introdução
*** Se você tirar comparar recortes da vida em vários momentos, a conclusão inevitável é de que viver é uma experiência fundamentalmente entediante
**** Esperar em filas de banco
**** Aguardar resultados de exames
**** Assistir a uma aula morosa
**** Andar até um ponto de ônibus
**** etc
*** Quando somos mais novos, temos perfeita noção disso: cada minuto vale 10, e os dias e anos se arrastam. Nós vamos até nossos pais e, com voz arrastada, reclamamos: "Que tédio"!
*** A sociedade lida com isto de maneira combativa. "Cabeça vazia, oficina do diabo"; "só quem é entediante fica entediado". Estar ocupado é ser útil.
*** Para alguns, o tédio é fonte real de problemas: violência, gravidez na adolescência, crianças piromaníacas. Para outros, essas coisas advém de outras questões do desenvolvimento cognitivo
** Atenção
*** Nosso cérebro não quer placidez. Se estamos desocupados, ele imediatamente começa a maquinar uma série de coisas. É como uma máquina da Amazon: tem capacidade livre, vamos alugar e ocupar com processamento útil
**** Os budistas têm um nome para isso: mente de macaco. Esse estado caracteriza a inquietude, os caprichos, a confusão e impulsividade aos quais nossas mentes se lançam sempre que não estamos num momento de função executiva
*** Sempre sofremos disso. A grande transformação na nossa *atitude* em relação a isso começa com a luz elétrica. Com ela, os dias passaram a ser mais longos, as opções mais vastas, e as chances de escapar ao turbilhão interno maiores
*** A evolução dessas vantagens recentes nos trouxe ao estado atual. Passamos de tardes chatas na casa de nossa avó nas férias de verão para um estado constante de ocupação mental: notificações de redes sociais e comunicadores instantâneos, checagens constantes de caixas de email. Não há espaço para o tédio. Não há tolerância para o vazio existencial que nos acomete sempre que estamos apenas com nossos pensamentos
*** Um outro fator que contribui para nossa sensação costante de ocupação são as mudanças de postura em relação ao trabalho: saímos dos extremos de 18h diárias de trabalho da revolução industrial para as conquistas que reduziram a jornada às 40h que conhecemos hoje. Com a transição da economia de produção para a economia intelectual e a ubiquidade do acesso que temos uns aos outros, essa jornada de trabalho tem estado cada vez maior
*** A pergunta que sempre devemos fazer quando o pêndulo vai de um extremo a outro muito rápido é: isso tudo é realmente bom?
** Economia de atenção
*** Centenas de negócios surgem todos os anos brigando pelo nosso tempo e atenção. A publicidade na TV é frequentemente apontada como um desses negócios. Mas há mais: o que são Twitter, Instagram, Facebook, até mesmo Waze? São meios pelos quais, fazer com que doemos de bom grado nossos instantes, oferecendo em troca dopamina e paliativos para os mais arraigado terrores do nosso lado gregário -- isto é, estar de fora do que está acontecendo com as pessoas de quem gostamos, de perder nossa relevância perante estas, etc.
*** Fragmentamos nossos dias em dezenas de microssatisfações que são tão duradouras quanto a saciedade de ter comido McDonald's. Como resultado, é um impulso natural querermos transformar essas dezenas em centenas, até que de algum modo atinjamos a plenitude
*** Há um nome para isso: "a economia da atenção". A atenção e tempo estão intimamente ligados, e são bens cujo valor não se mensura. Ao contrário de dinheiro, não há como ter mais de um ou de outro. A ignorância deste fato faz com que vivenciemos o pico de nossa vida produtiva como um preparativo para o momento em que aproveitaremos todos os benefícios da improdutividade. Quando o momento chega, estamos na merda física e mentalmente
** O tédio é um privilégio
*** Quando pensamos em quem está entediado normalmente, há quatro grupos principais: crianças, adolescentes, velhos e desempregados. Desta maneira, o tédio ganha a pecha de algo indesejável, algo associado apenas à imaturidade e à penúria
*** Eu entendo o tédio de maneira mais virtuosa: ele é um privilégio. O que é que tédio representa (numa vida saudável nos aspectos primordiais) se não uma evidência de que a única obrigação naquele momento é estar consigo mesmo, absorto nos próprios pensamentos?
*** O termo em alemão para tédio é "langeweile". "Lang" - longo; "weile" - período. Quando se está entediado o tempo passa devagar como passava na infância. Este é o momento para se buscar paz com nossas próprias mentes. Para tentar entrar em contato com ideias mais complicadas, tentar sentir a textura da realidade, explorar novas ideias
*** Se você está entediado, isso significa que sua mente está livre. É a chance que você tem de ser fiel às suas vontades e seus valores, de pensar no que você está pensando -- chance esta que prontamente temos substituído por telas, por um ideal de diversão. Agarre-a. Obrigado.

